### ISSUE TITLE
Episode 4 - Whitni's website page has changed

### ISSUE THREAD

**Issue by HeofHIShirts** [thatandromeda/open_paren#11]
Enjoyed listening to Whitni Watkins on Episode 4. 

It looks like https://nimblelibrarian.com, Whitni's mentioned website, is a 404 at the moment, but it looks like their web presence exists at https://nimblelibrarian.wordpress.com

Thanks for putting on the podcast!

**Comment by thatandromeda** [comment]
Thanks! Fixed now (may take up to 10 minutes to propagate).
