### ISSUE TITLE
Episode 5 - Margaret Heller's website

### ISSUE THREAD

**Issue by HeofHIShirts** [thatandromeda/open_paren#12]
The website for Margaret Heller has the right display name, but it thinks that Glorious Generalist is a subdomain of open_paren, so it 404 errors out when you try to click on it.

http://openparen.club/www.gloriousgeneralist.com is what it thinks should happen. Probably just an errant Markdown thing done or not done.

(Promise, this is the last oops up to the current episode, right?)

**Comment by thatandromeda** [comment]
Thanks! Fixed.
