### ISSUE TITLE
Make gh-pages default branch?

### ISSUE THREAD

**Issue by brianzelip** [thatandromeda/open_paren#2]
You can make the gh-pages branch the default branch for the open paren repo (Settings > Branches > Default branch).

When the master branch is set (like it currently is), all visitors initially see is an empty readme and `.gitignore`. Might be confusing to folks not familiar w/ github, like, "where's the goods?"

**Comment by thatandromeda** [comment]
I did not know that was an option! Thanks; you're right; I did want that to be the default. Done.
