### ISSUE TITLE
Website links to podcast are going to 404 page

### ISSUE THREAD

**Issue by jschwarzwalder** [thatandromeda/open_paren#3]
I went to http://thatandromeda.github.io/open_paren/ to possibly listen to learn more about the project and maybe listen to one of the podcasts, however the links do not include the /open_paren/ folder so they are going to 404 pages.

When I add /open_paren/ to the url it does seem to go to the correct page.

**Comment by thatandromeda** [comment]
This is the same issue as #4 , so I'm going to close this one.
