### ISSUE TITLE
Stylesheet isn't being loaded

### ISSUE THREAD

**Issue by jschwarzwalder** [thatandromeda/open_paren#4]
This is likely the same issue as previously reported, but their are no styles loaded onto the website http://thatandromeda.github.io/open_paren/

When I look at your code it seems that you have relative links for the style sheet, so it could be fixed if you make sure the files are inside the /open_paren/ folder.

**Comment by thatandromeda** [comment]
It is the same issue. I got a new URL - openparen.club - and if you use that you'll see the stylesheet loaded; unfortunately, when I made things work for that URL it broke them for the github URL. Similarly, I'm pretty sure that creating an open_paren folder and moving content there would break things for the openparen.club URL. I need a solution that works for both, and I haven't had time to prioritize that. Ideas which make both URLs work are welcome :)

**Comment by jschwarzwalder** [comment]
I've not used Jekyll, but I can read up on it to see if I can find a solution. 

Does this make any sense to you?

I noticed in your `_config.yml` file you commented out the variable baseurl. Was it interfering with making openparen.club work properly.

Do you have a hosting plan from Namecheap for openparen.club or are you using domain masking?

**Comment by jschwarzwalder** [comment]
The github.io site redirects to openparen.club, so issue is resolved.
