### ISSUE TITLE
link to home, has no href text to take you to the index.html

### ISSUE THREAD

**Issue by jschwarzwalder** [thatandromeda/open_paren#5]
On both the https://thatandromeda.github.io/open_paren/ and http://openparen.club/ websites when you click on home there are no instructions to tell the browser where to go, so it just reloads the page

line 25 in index.html `<li><a href="">Home</a></li>`

It would probably workfor now if you changed your header file to  `<li><a href="index.html">Home</a></li>`

I am not sure why the `{{ site.baseurl }}` doesn't seem to be working. When I inspect your files I see relative links to the pages.

**Comment by thatandromeda** [comment]
This is also a site.baseurl configuration problem, like #4 . Closing in order to keep everything consolidated in one issue.
